version: "{build}-{branch}"
image: Visual Studio 2017

init:
  - ps: '(Get-ChildItem -Path "Env:").Where({ $_.Name -match "^(?:BH|CI(?:_|$)|APPVEYOR)" })'
install:
  - ps: .\install.ps1
build_script:
  - ps: .\build.ps1
after_build:
  - ps: .\release.ps1
  - on:
    APPVEYOR_REPO_TAG: true

artifacts:
  - path: 'build\*'
    name: release

deploy:
  description: '$(GITHUB_RELEASE_NOTES)'
  provider: GitHub
  auth_token:
    secure: TpQW7XTUsFihAjHMpMhMSKNyxF/6WVuEloQxniIajPtQSfBd8X91jUJAR4TZxn8o
  artifact: 'release'
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
